name: .NET

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release
    strategy:
      matrix:
        kind: ['linux', 'windows', 'macOS']
        include:
          - kind: linux
            os: ubuntu-22.04
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64
          - kind: macOS
            os: macos-latest
            target: osx-x64

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 10.0.x

    - name: Restore dependencies
      run: dotnet restore ./quantized-mesh-tile-cs.slnx

    - name: Build
      run: dotnet build ./quantized-mesh-tile-cs.slnx --no-restore -c Release

    - name: Test
      run: dotnet test ./quantized-mesh-tile-cs.slnx --no-build --verbosity normal

    - name: Publish qm-tools
      working-directory: ./qm-tools
      shell: bash
      run: |
        dotnet tool install -g dotnetCampus.TagToVersion
        dotnet build -c Release
        dotnet TagToVersion -t ${{ github.ref }}
        echo tag found: ${{ github.ref }}
        dotnet publish -c Release -r ${{ matrix.target }} -o publish
        rm -f ./publish/*.pdb
        cd publish
        if [ "${{ matrix.target }}" == "win-x64" ]; then
          7z a -tzip ../qmtools-${{ matrix.target }}.zip .
        else
          tar czvf ../qmtools-${{ matrix.target }}.tar.gz .
        fi

    - name: Publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: softprops/action-gh-release@v1
      with:
        files: "./qm-tools/qmtools-${{ matrix.target }}.*"